// <auto-generated />
using System;
using DiningGuideRemake.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiningGuideRemake.Migrations
{
    [DbContext(typeof(DiningGuideData))]
    [Migration("20210619072006_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DiningGuideRemake.Models.Rate", b =>
                {
                    b.Property<int>("IDReview")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDRestaurant")
                        .HasColumnType("int");

                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<double>("Rating1")
                        .HasColumnType("float")
                        .HasColumnName("Rating");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDReview");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("DiningGuideRemake.Models.Restaurant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Decription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDUser")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RateIDReview")
                        .HasColumnType("int");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("RateIDReview");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("DiningGuideRemake.Models.User", b =>
                {
                    b.Property<int>("idUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("RateIDReview")
                        .HasColumnType("int");

                    b.Property<int?>("RestaurantID")
                        .HasColumnType("int");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("idUser");

                    b.HasIndex("RateIDReview");

                    b.HasIndex("RestaurantID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiningGuideRemake.Models.Restaurant", b =>
                {
                    b.HasOne("DiningGuideRemake.Models.Rate", "Rate")
                        .WithMany("Restaurants")
                        .HasForeignKey("RateIDReview");

                    b.Navigation("Rate");
                });

            modelBuilder.Entity("DiningGuideRemake.Models.User", b =>
                {
                    b.HasOne("DiningGuideRemake.Models.Rate", "Rate")
                        .WithMany("Users")
                        .HasForeignKey("RateIDReview");

                    b.HasOne("DiningGuideRemake.Models.Restaurant", "Restaurant")
                        .WithMany("Users")
                        .HasForeignKey("RestaurantID");

                    b.Navigation("Rate");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("DiningGuideRemake.Models.Rate", b =>
                {
                    b.Navigation("Restaurants");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DiningGuideRemake.Models.Restaurant", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
